version: '3.9'

services:
  api:
    container_name: app_api
    build: .
    restart: always
    env_file: .env.dev
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --no-input && gunicorn core_root.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - app_volume:/app/uploads
    depends_on:
      - core_db
      - redis

  core_db:
    container_name: core_db
    image: postgres:14.3-alpine
    env_file: .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine


volumes:
  app_volume:
  postgres_data:
