# Generated by Django 4.2.3 on 2023-07-05 11:51

from django.db import migrations, models

import core.user.models


class Migration(migrations.Migration):
    dependencies = [
        ('core_user', '0002_user_posts_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.user.models.user_directory_path),
        ),
    ]
